version: '3'

services:
  drill-admin:
    image: drill4j/admin:0.5.0-rc1
    environment:
      - T2CM_VERSION=0.5.0-rc1
    ports:
      - 8090:8090
      - 5006:5006
    networks:
      - drill4j-dev-network
    restart: always

  admin-ui:
    image: drill4j/admin-ui:0.5.0-rc1
    ports:
      - 8091:8080
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network
